### ISSUE TITLE
Where did this project go?

### ISSUE THREAD

**Issue by itsrachelfish** [Lessig2016/campaign#1]
A few days ago this repo contained the wordpress installation for lessig's campaign site. Then, yesterday it was deleted. Now it's back but with only a single readme file?

I'm guessing the project had to be deleted for security reasons, or maybe licensing issues (since wordpress is GPL).

Either way, it'd be nice to know what happened!

Thanks

:sparkling_heart: :octocat:

**Comment by aaronlifshin** [comment]
We had moved that repo and then made changes to the older private repo.
Basically, there was some confusion between the check-ins.

The challenge at the moment is that we don't have a good dev process for
allowing people to contribute to our wordpress repo, and we are working on
a way to do that.

Any thoughts on how to accomplish that?

A

**Comment by itsrachelfish** [comment]
It's hard to give an answer without knowing what your setup is and what the differences are between your public and private repos. But... I can guess.

### One way you could do it

At the very least you'll want to have a public and a private repo. The public repo would have your wordpress installation and theme, plus a gitignore file to hide all of your secrets. The private repo would have all of your secrets (configuration files, certain plugins, etc), plus a script to create symlinks.

When deploying to a server, you'd clone the public repo, then the private repo, then run the script to create the symlinks. This would let you keep things separate but still give you a way to internally track private changes.

When another developer like me comes along, all I'd have to do is clone the public repo and use my own wp-config file. There are [plenty of sites](https://generatewp.com/wp-config/) that can help generate wp-config files, so this should be simple enough for anyone familiar with wordpress.

### Other ideas

It's fairly common to use a wp-config file that detects what configuration should be used based on the existence of a file, for example: https://github.com/sohooo/wp-capify/blob/0fc6b2f769c867e467c43ff24e017b0f5fe3a2bc/config/bootstrap/templates/wp-config.php

Also... you probably don't want to keep a specific list of all your secret files in a .gitignore. Instead, you could use generic rules like "gitignore all plugins starting with an underscore" or "gitignore everything that ends in .config.php"

Let me know if that helps, or maybe some more information about the specific challenges you're facing.

:shipit:

**Comment by aaronlifshin** [comment]
I think the issue is that a lot of the wordpress pages (the content that we
actually work with and change every day) are stored in a database on the
server.

Sean knows this better than I do, but I think that's the case.

So, just putting the wordpress files into GH would not really give anyone
access to all the pages which are in the database.

We use Visual Composer, BTW.

A

**Comment by itsrachelfish** [comment]
Happy to see this repo full of stuff again! :cherry_blossom:
