### ISSUE TITLE
Header Logos Overlapping 

### ISSUE THREAD

**Issue by dsuffern** [Lessig2016/campaign#12]
The two logos are overlapping one another on both 

**http://www.lessigforpresident.com/home/**
**https://lessig2016.us/home/**

 [Image of Said Issue](https://cloud.githubusercontent.com/assets/1696706/10556777/e4e575de-7453-11e5-9a4c-518c9b758a8c.png)

**Comment by furf** [comment]
do you recall how you got to those pages? from which pages/links?

**Comment by dsuffern** [comment]
I'll track it down and get back to you - however I noticed there are no
301s from the hime directory, and it looked as though they might be getting
crawled differently than the root WP install. Can't confirm the last part
though.

I know I found the link organically, or as a referral. Il run a quick
backlinks scan in OSE, AHREFs and Majestic.

**Comment by petergreeen** [comment]
this is an old home page that's not used anymore

**Comment by dsuffern** [comment]
Regardless, it was still publicly accessible via inbound links/search engines and there was no 301 redirect present

**Comment by petergreeen** [comment]
good call. added some 301s

Peter Green

858 952 6505
peter.a.green@gmail.com
freemoneybaby.co
